# Generated by Django 2.2.16 on 2022-04-19 21:39

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(blank=True, max_length=7, validators=[tags.models.hex_code_validator], verbose_name='Цвет, HEX-code')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('name',),
            },
        ),
    ]
