# Generated by Django 2.2.16 on 2022-04-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220421_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desc',
            new_name='text',
        ),
    ]
